In [22]:
import sqlite3
import pandas as pd
con=sqlite3.connect('../data/raw/ipl.db')

def q(sql):
    return pd.read_sql(sql, con)

In [23]:
def run_sql_file(path):
    with open(path, 'r') as f:
        script = f.read()
    con.executescript(script)
    con.commit()
    print('ran',path)

In [24]:
q("""
-- what is the strike rate of every batter in the death overs

SELECT 
    batter,
    ROUND(
        100.0*SUM(batter_runs)/SUM(
            case
                WHEN is_wide_ball=0 AND is_no_ball=0
                THEN 1
                ELSE 0
            END 
        ),2) 
    AS strike_rate

FROM deliveries
WHERE over_number >= 15 AND is_super_over = 0
GROUP BY batter;""")

             batter  strike_rate
0    A Ashish Reddy       146.58
1          A Badoni       165.03
2        A Chandila        57.14
3          A Chopra        50.00
4       A Choudhary       125.00
..              ...          ...
637      Yash Dayal        50.00
638   Yashpal Singh       130.77
639   Yudhvir Singh       166.67
640    Yuvraj Singh       183.40
641          Z Khan       100.00

[642 rows x 2 columns]

In [34]:
run_sql_file('../sql/09_analysis_views.sql')

ran ../sql/09_analysis_views.sql

In [26]:
q("""SELECT * 
    FROM v_ball""")

,season_id,match_id,batter,bowler,non_striker,over_number,ball_number,batter_runs,extras,total_runs,...,is_super_over,innings,batting_team_id,bowling_team_id,batting_team,bowling_team,phase,is_legal,bowler_runs,bowler_wicket
0,2008,335982,SC Ganguly,P Kumar,BB McCullum,0,0,0,1,1,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,0,0
1,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,1,0,0,0,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,0,0
2,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,2,0,1,1,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,0,1,0
3,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,3,0,0,0,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,0,0
4,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,4,0,0,0,...,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore,Powerplay,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
288046,2026,1529286,T Stubbs,JC Archer,Ashutosh Sharma,18,3,1,0,1,...,0,2,252,134,Delhi Capitals,Rajasthan Royals,Death,1,1,0
288047,2026,1529286,Ashutosh Sharma,JC Archer,T Stubbs,18,4,1,0,1,...,0,2,252,134,Delhi Capitals,Rajasthan Royals,Death,1,1,0
288048,2026,1529286,T Stubbs,JC Archer,Ashutosh Sharma,18,5,4,0,4,...,0,2,252,134,Delhi Capitals,Rajasthan Royals,Death,1,4,0
288049,2026,1529286,Ashutosh Sharma,Brijesh Sharma,T Stubbs,19,0,4,0,4,...,0,2,252,134,Delhi Capitals,Rajasthan Royals,Death,1,4,0
288050,2026,1529286,Ashutosh Sharma,Brijesh Sharma,T Stubbs,19,1,0,1,1,...,0,2,252,134,Delhi Capitals,Rajasthan Royals,Death,0,1,0

In [27]:
q("""SELECT phase, COUNT(*) FROM v_ball
GROUP BY phase;""")

       phase  COUNT(*)
0      Death     65488
1     Middle    132173
2  Powerplay     90390

In [28]:
q("""SELECT * FROM v_innings""")

,match_id,innings,batting_team,bowling_team,runs,wickets,legal_balls
0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,222,3,120
1,335982,2,Royal Challengers Bangalore,Kolkata Knight Riders,82,10,91
2,335983,1,Chennai Super Kings,Punjab Kings,240,5,120
3,335983,2,Punjab Kings,Chennai Super Kings,207,4,120
4,335984,1,Rajasthan Royals,Delhi Capitals,129,8,120
...,...,...,...,...,...,...,...
2413,1529284,2,Sunrisers Hyderabad,Mumbai Indians,249,4,112
2414,1529285,1,Royal Challengers Bangalore,Gujarat Titans,155,10,116
2415,1529285,2,Gujarat Titans,Royal Challengers Bangalore,158,6,95
2416,1529286,1,Rajasthan Royals,Delhi Capitals,225,6,120
2417,1529286,2,Delhi Capitals,Rajasthan Royals,226,3,115

In [35]:
q("""SELECT COUNT(*) FROM v_match_totals""")

   COUNT(*)
0      1187

In [36]:
q("""SELECT COUNT(*) FROM v_innings""")

   COUNT(*)
0      2418

In [38]:
q("""SELECT phase,COUNT(*) FROM v_ball""")

       phase  COUNT(*)
0  Powerplay    288051